CapaPresentationUser/Controllers/AccesoController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace CapaPresentationUser.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult CambiarClave()
        {
            return View();
        }

        public ActionResult Reestablecer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string correo, string clave)
        {
            Usuarios oUsuario = new Usuarios();

            oUsuario = new CN_Usuarios().Listar().Where(u => u.Correo == correo && u.Clave == CN_Recursos.ConvertirSha256(clave)).FirstOrDefault();

            if (oUsuario == null)
            {
                ViewBag.Error = "Correo o contraseña no correcta";
                return View();
            }
            else
            {
                if (oUsuario.Reestablecer)
                {
                    TempData["IdUsuario"] = oUsuario.IdUsuario;
                    return RedirectToAction("CambiarClave", "Acceso");
                }

                FormsAuthentication.SetAuthCookie(oUsuario.Correo, false);

                Session["Usuario"] = oUsuario;

                
                if (oUsuario.Correo == "intellecdata.soporte@gmail.com")
                {
                    Session["UserRole"] = "Admin";
                    ViewBag.Error = null;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    Session["UserRole"] = "User";
                    ViewBag.Error = null;
                    return RedirectToAction("IndexUser", "Home");
                }

            }
        }

        [HttpPost]
        public ActionResult CambiarClave(string idusuario, string claveactual, string nuevaclave, string confirmarclave)
        {
            Usuarios oUsuario = new Usuarios();
            oUsuario = new CN_Usuarios().Listar().Where(u => u.IdUsuario == int.Parse(idusuario)).FirstOrDefault();

            if (oUsuario.Clave != CN_Recursos.ConvertirSha256(claveactual))
            {
                TempData["IdUsuario"] = idusuario;
                ViewData["vclave"] = "";
                ViewBag.Error = "La contraseña no es correcta";
                return View();
            }
            else if (nuevaclave != confirmarclave)
            {
                TempData["IdUsuario"] = idusuario;
                ViewData["vclave"] = claveactual;
                ViewBag.Error = "Las contraseñan no coindicen";
                return View();
            }

            ViewData["vclave"] = "";

            nuevaclave = CN_Recursos.ConvertirSha256(nuevaclave);

            string mensaje = string.Empty;
            bool respuesta = new CN_Usuarios().CambiarClave(int.Parse(idusuario), nuevaclave, out mensaje);

            if (respuesta)
            {
                return RedirectToAction("Index", "Acceso");
            }
            else
            {
                TempData["IdUsuario"] = idusuario;
                ViewBag.Error = mensaje;
                return View();
            }

        }


        [HttpPost]
        public ActionResult Reestablecer(string correo)
        {
            Usuarios oUsuario = new Usuarios();
            oUsuario = new CN_Usuarios().Listar().Where(item => item.Correo == correo).FirstOrDefault();

            if (oUsuario == null)
            {
                ViewBag.Error = "No se encontró un usuario relacionado a este correo";
                return View();
            }

            string mensaje = string.Empty;
            bool respuesta = new CN_Usuarios().ReestablecerClave(oUsuario.IdUsuario, correo, out mensaje);


            if (respuesta)
            {
                ViewBag.Error = null;
                return RedirectToAction("Index", "Acceso");
            }
            else
            {
                ViewBag.Error = mensaje;
                return View();
            }
        }

        public ActionResult CerrarSesion()
        {
            Session["Usuario"] = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Acceso");
        }
    }
}

CapaPresentationUser/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CapaEntidad;
using CapaNegocio;

namespace CapaPresentationUser.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Clientes()
        {
            return View();
        }
    }
}

CapaPresentationUser/Controllers/MantenedorController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentationUser.Controllers
{
    public class MantenedorController : Controller
    {
        // GET: Mantenedor
        public ActionResult Tickets()
        {
            return View();
        }

        public ActionResult PreguntasFrecuentes()
        {
            return View();
        }


        [HttpGet]
        public JsonResult ListarTickets()
        {
            List<Ticket> oLista = new List<Ticket>();
            oLista = new CN_Ticket().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult GuardarTicket(Ticket objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            objeto.oUsuario.IdUsuario = ((Usuarios)Session["Usuario"]).IdUsuario;

            if (objeto.IdTicket == 0)
            {
                resultado = new CN_Ticket().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Ticket().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult EliminarTicket(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;


            respuesta = new CN_Ticket().Eliminar(id, out mensaje);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
    }
}

CapaPresentationUser/Views/Home/Clientes.cshtml
@{
    ViewBag.Title = "Clientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Análisis</a></li>
    <li class="breadcrumb-item active">Clientes</li>
</ol>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <a href="URL_DEL_INFORME_1" class="card h-100 text-decoration-none">
                <div class="card-header text-white" style="background-color: #FFA500;">
                    1. Daily Sellout
                </div>
                <div class="card-body text-center">
                    <i class="bi bi-bar-chart-fill" style="font-size: 4rem;"></i>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a href="URL_DEL_INFORME_2" class="card h-100 text-decoration-none">
                <div class="card-header text-white" style="background-color: #FFA500;">
                    2. Reporte de Concursos
                </div>
                <div class="card-body text-center">
                    <i class="bi bi-trophy-fill" style="font-size: 4rem;"></i>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a href="URL_DEL_INFORME_3" class="card h-100 text-decoration-none">
                <div class="card-header text-white" style="background-color: #FFA500;">
                    3. Tracker Sachets
                </div>
                <div class="card-body text-center">
                    <i class="bi bi-bag-fill" style="font-size: 4rem;"></i>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a href="URL_DEL_INFORME_4" class="card h-100 text-decoration-none">
                <div class="card-header text-white" style="background-color: #FFA500;">
                    Maestro Productos
                </div>
                <div class="card-body text-center">
                    <i class="bi bi-box-seam" style="font-size: 4rem;"></i>
                </div>
            </a>
        </div>
    </div>
</div>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

CapaPresentationUser/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

CapaPresentationUser/Views/Mantenedor/PreguntasFrecuentes.cshtml
@{
    ViewBag.Title = "PreguntasFrecuentes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PreguntasFrecuentes</h2>

CapaPresentationUser/Views/Mantenedor/Tickets.cshtml
@{
    ViewBag.Title = "Tickets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Tickets</li>
</ol>


<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i> Lista de Tickets
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Nuevo Ticket</button>
            </div>
        </div>

        <hr />

        <table id="tabla_ticket" class="display cell-border" style="width: 100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Correo</th>
                    <th>Asunto</th>
                    <th>Prioridad</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Ticket</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <input id="txtid" type="hidden" value="0" />

                <div class="row g-2">
                    <div class="col-sm-6">
                        <label for="txtnombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="txtnombre" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="txtcorreo" class="form-label">Correo</label>
                        <input type="text" class="form-control" id="txtcorreo" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="txtasunto" class="form-label">Asunto</label>
                        <input type="text" class="form-control" id="txtasunto" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboprioridad" class="form-label">Prioridad</label>
                        <select id="cboprioridad" class="form-select">
                            <option value="1">Baja</option>
                            <option value="0">Alta</option>
                        </select>
                    </div>

                    <div class="col-sm-6">
                        <label for="cboestado" class="form-label">Estado</label>
                        <select id="cboestado" class="form-select">
                            <option value="1">Pendiente</option>
                            <option value="0">Resuelto</option>
                        </select>
                    </div>

                </div>

                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts{

    <script>

        var tabladata;
        var filaSeleccionada;

        tabladata = $("#tabla_ticket").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarTickets", "Mantenedor")',
                type: "GET",
                datatype: "json"
            },
            "columns": [
                { "data": "oUsuario", "render": function(data) {
                    return data.Nombre
                    }
                },
                {
                    "data": "oUsuario", "render": function (data) {
                        return data.Correo
                    }
                },
                { "data": "Asunto" },
                {
                    "data": "Prioridad", "render": function (valor) {
                        if (valor) {
                            return '<span class="badge bg-success">Baja</span>'
                        } else {
                            return '<span class="badge bg-danger">Alta</span>'
                        }
                    }
                },
                {
                    "data": "Estado", "render": function(valor){
                        if (valor) {
                            return '<span class="badge bg-danger">Pendiente</span>'
                        } else {
                            return '<span class="badge bg-success">Resuelto</span>'
                        }
                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"
                }
            ],
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            }

        });




        function abrirModal(json) {

            $("#txtid").val(0);
            $("#txtnombres").val("");
            $("#txtapellidos").val("");
            $("#txtcorreo").val("");
            $("#cboestado").val(1);

            $("#mensajeError").hide();

            if (json != null) {

                $("#txtid").val(json.IdUsuario);
                $("#txtnombres").val(json.Nombre);
                $("#txtapellidos").val(json.Apellidos);
                $("#txtcorreo").val(json.Correo);
                $("#cboestado").val(json.Estado == true ? 1 : 0);

            }


            $("#FormModal").modal("show");

        }

        $("#tabla_user tbody").on("click", '.btn-editar', function () {
            var filaSeleccionada = $(this).closest("tr");
            var data = tabladata.row(filaSeleccionada).data();
            abrirModal(data);

        })

        $("#tabla_user tbody").on("click", '.btn-eliminar', function () {
            var usuarioseleccionado = $(this).closest("tr");

            var data = tabladata.row(usuarioseleccionado).data();

            swal({
                title: "ATENCION",
                text: "¿Desea eliminar el usuario?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtontext: "Si",
                cancelButtontext: "No",
                closeOnconfirm: true

            }, function () {

                jQuery.ajax({

                    url: '@Url.Action("EliminarUsuario","Mantenedor")',
                    type: "POST",
                    data: JSON.stringify({ id: data.IdUsuario }),
                    datatype: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.resultado) {
                            tabladata.row(usuarioseleccionado).remove().draw();
                        } else {
                            swal("No se puedo eliminar", data.mensaje, "error");
                        }

                    },
                    error: function (error) {
                        $(".modal-body").LoadingOverlay("hide");
                        $("#mensajeError").text("Error Ajax");
                        $("#mensajeError").show();
                    }


                });



            });

        })


        function Guardar() {

            var Usuario = {
                IdUsuario: $("#txtid").val(),
                Estado: $("#cboestado").val() == 1 ? true : false,
                Apellidos: $("#txtapellidos").val(),
                Correo: $("#txtcorreo").val(),
                Nombre: $("#txtnombres").val()
            }


            jQuery.ajax({

                url: '@Url.Action("GuardarUsuario","Mantenedor")',
                type: "POST",
                data: JSON.stringify({ objeto: Usuario}),
                datatype: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide");

                    //USUARIO NUEVO
                    if (Usuario.IdUsuario == 0) {

                        if (data.resultado != 0) {
                            Usuario.IdUsuario = data.resultado;
                            tabladata.row.add(Usuario).draw(false);
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                    //USUARIO EDITADO
                    else {

                        if (data.resultado) {
                            tabladata.row(filaSeleccionada).data(Usuario).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show"), {
                        imageResizrFactor: 2,
                        text: "Cargando...",
                        size: 14
                    }

                }


            });

        }



    </script>

}

CapaPresentationUser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">INTELLECDATA</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*@<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion","Acceso")">Cerrar Sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Ventas
                        </a>
                        <a class="nav-link" href="@Url.Action("Clientes","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Clientes
                        </a>
                        @*<div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Layouts
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Pages
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>*@
                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" href="@Url.Action("Tickets","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tickets
                        </a>
                        <a class="nav-link" href="@Url.Action("PreguntasFrecuentes","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-question"></i></div>
                            Preguntas Frecuentes
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()



                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>







    @*@RenderBody()
        <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>